"""Automatic PoC generation for confirmed findings.

Produces reproducible curl commands, standalone Python scripts, and
formatted terminal output for each finding.
"""

from __future__ import annotations

import json
import urllib.parse
from typing import Optional

from pathprobe.core.types import Finding


class PoCGenerator:
    """Generate proof-of-concept artefacts for each finding."""

    def curl(self, finding: Finding) -> str:
        """Generate a curl command that reproduces the finding."""
        parts = ["curl", "-v", "--path-as-is"]
        pm = finding.post_mode

        if pm == "GET" or pm is None:
            # Reconstruct URL with payload in query string
            parsed = urllib.parse.urlparse(finding.url)
            qs = urllib.parse.parse_qs(parsed.query, keep_blank_values=True)
            qs[finding.param] = [finding.payload]
            full_url = parsed._replace(
                query=urllib.parse.urlencode(qs, doseq=True),
            ).geturl()
            parts.append(f"'{full_url}'")
        else:
            parts.extend(["-X", "POST", f"'{finding.url}'"])
            if pm == "json":
                data = json.dumps({finding.param: finding.payload})
                parts.extend([
                    "-H", "'Content-Type: application/json'",
                    "-d", f"'{data}'",
                ])
            elif pm == "form":
                encoded = urllib.parse.urlencode({
                    finding.param: finding.payload,
                })
                parts.extend(["-d", f"'{encoded}'"])
            elif pm == "xml":
                xml = (f'<?xml version="1.0"?>'
                       f'<request><{finding.param}>{finding.payload}'
                       f'</{finding.param}></request>')
                parts.extend([
                    "-H", "'Content-Type: application/xml'",
                    "-d", f"'{xml}'",
                ])
            elif pm == "multipart":
                parts.extend([
                    "-F", f"'{finding.param}=@-;filename={finding.payload}'",
                ])

        # WAF bypass headers
        if finding.waf_technique and finding.waf_technique != "none":
            parts.extend([
                "-H", "'X-Forwarded-For: 127.0.0.1'",
                "-H", "'X-Real-IP: 127.0.0.1'",
            ])

        parts.append("--insecure")
        return " \\\n  ".join(parts)

    def python_script(self, finding: Finding) -> str:
        """Generate a standalone Python PoC script."""
        pm = finding.post_mode
        if pm == "GET" or pm is None:
            request_code = (
                f'resp = requests.get(url, params={{"{finding.param}": payload}}, '
                f"verify=False, timeout=15)"
            )
        elif pm == "json":
            request_code = (
                f'resp = requests.post(url, json={{"{finding.param}": payload}}, '
                f"verify=False, timeout=15)"
            )
        elif pm == "form":
            request_code = (
                f'resp = requests.post(url, data={{"{finding.param}": payload}}, '
                f"verify=False, timeout=15)"
            )
        else:
            request_code = (
                f"# Adjust for {pm} content type\n"
                f'resp = requests.post(url, data={{"{finding.param}": payload}}, '
                f"verify=False, timeout=15)"
            )

        return f'''#!/usr/bin/env python3
"""
PoC: Path Traversal — {finding.param} parameter
Target:     {finding.url}
Severity:   {finding.severity}
Confidence: {finding.confidence} ({finding.confidence_score}/100)
Generated by PathProbe v3.0
"""
import requests
import urllib3
urllib3.disable_warnings()

url     = "{finding.url}"
payload = "{finding.payload}"

{request_code}

print(f"Status: {{resp.status_code}}")
print(f"Length: {{len(resp.text)}}")
print(f"Content-Type: {{resp.headers.get('Content-Type', 'unknown')}}")
print(f"\\nBody preview:\\n{{resp.text[:500]}}")
'''

    def terminal_block(self, finding: Finding, index: int) -> str:
        """Format a single finding as a rich terminal block."""
        score = finding.confidence_score
        bar = '█' * (score // 5) + '░' * (20 - score // 5)
        verified = "✓ YES" if finding.verified else "✗ No"

        sigs = ""
        for m in finding.signatures:
            sigs += f"\n║    [{m.severity}] {m.description} (OS: {m.os})"

        curl_cmd = self.curl(finding)
        curl_lines = curl_cmd.replace("\n", "\n║  ")

        return f"""
╔══════════════════════════════════════════════════════════════╗
║  FINDING #{index}  —  Score: {score}/100  [{bar}]
╠══════════════════════════════════════════════════════════════╣
║  Parameter : {finding.param}
║  Payload   : {finding.payload[:60]}
║  Method    : {finding.post_mode}
║  Status    : {finding.status}
║  WAF Bypass: {finding.waf_technique}
║  Verified  : {verified}
╠══════════════════════════════════════════════════════════════╣
║  Signatures:{sigs}
╠══════════════════════════════════════════════════════════════╣
║  PoC (curl):
║  {curl_lines}
╚══════════════════════════════════════════════════════════════╝"""
